### ISSUE TITLE
azd up fails to deploy chat service

### ISSUE THREAD

**Issue by prasanna-h-krishnan** [Azure-Samples/contoso-chat#152] opened 2024-08-27 19:45 UTC
### This issue is for a: (mark with an `x`)
```
- [x] bug report -> please search issues before submitting
```
### Describe the issue
When I run azd up (or azd deploy post provisioning), the deployment step fails and I get the below error instead - 

> Code: AuthorizationFailed
Message: The client 'myuser@microsoft.com' with object id 'xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx' does not have authorization to perform action 'Microsoft.MachineLearningServices/workspaces/datastores/read' over scope '/subscriptions/<my-sub-id>/resourceGroups/rg-contoso-chat-main/providers/Microsoft.MachineLearningServices/workspaces/ai-project-xxxxxx/datastores/workspaceblobstore' or the scope is invalid. If access was recently granted, please refresh your credentials.

1. I checked that the Azure Ai project resource provisioned contains the necessary permissions. 
2. But I notice that the object id from the error is different than the object id that was used during provisioning and the one with the necessary permissions which explains why I get this error. The object id from the error corresponds to my management tenant and not my home tenant.
3. I'm not sure why there is a discrepancy in the object ids used in the provisioning step vs the deployment step i.e. why is the deploy step not using the object id from my home tenant but instead using the object id from my managedByTenant?

### Minimal steps to reproduce
> Log in to az cli using  az login --tenant 'my-tenant-id'
Log in to azd cli using az auth login --tenant-id 'my-tenant-id'
run 'azd up'

'Provisioning Azure resources' and post-provisioning hooks are complete. 
'Deploying services (azd deploy)' step starts and terminates with the above error

### Expected/desired behavior
Deployment step should be completed and the deployment endpoint should be available

### Versions
I run into this error while deploying the 'main' branch version. I get the same error with GH Codespaces and devcontainer within vscode.

**Comment by jsburckhardt** [comment] 2024-09-04 23:27
I'm experiencing the same issue but I don't think is an issue with the repo. I think the issue is with AZD and the way creds are pass to the python connector. 
For now, the way I resolved it was using a SP from the landing tenant.

**Comment by sudivate** [comment] 2024-09-05 00:33
@jsburckhardt. Yes the issue is with way the AZD assumes home tenant. We reported this issue to AZD team and is been tracked here 
https://github.com/Azure/azure-dev/issues/4293

**Comment by cassiebreviu** [comment] 2024-09-05 00:34
Closing issue since its been reported to AZD.

**Closed by cassiebreviu** 2024-09-05 00:34 UTC

**Comment by jsburckhardt** [comment] 2024-09-06 08:37
> We reported this issue to AZD tea

after trying the deployment it failed because of a role to cosmos db. Posted the solution I ended doing the use referred here:


> @jsburckhardt. Yes the issue is with way the AZD assumes home tenant. We reported this issue to AZD team and is been tracked here [Azure/azure-dev#4293](https://github.com/Azure/azure-dev/issues/4293)
